config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users

  root to: "static_pages#index"

  namespace :admins do
    root to: "dashboards#index"
    resources :categories
    resources :topics
    resources :posts do
      resources :votes, only: %i(create)
      resources :comments, only: %i(create show update destroy)
    end
    resources :morderators, only: %i(index show create destroy)
    resources :users
    resources :images, only: [:create]
    resources :notifications, only: [:update]

    get "user_info"
    get "add_or_minus_moderators/:user_id/category/:id", to: "categories#add_or_minus_morderator", as: "add_or_minus_morderator"
    get "ban_or_unban_authors/:user_id/category/:id", to: "categories#ban_or_unban_authors", as: "ban_or_unban_author"
    get "ban_or_unban_authors/:user_id/topic/:id", to: "topics#ban_or_unban_authors", as: "ban_or_unban_author_topic"
  end

  namespace :morderators do

  end

  namespace :authors do
    root to: "posts#index"

    resources :posts
    resources :topics
  end
end

app/models/category.rb
class Category < ApplicationRecord
  enum status: %i(unpublish publish)

  CATEGORY_ATTRS = %w(id title description status user_id).freeze

  belongs_to :admin, class_name: User.name, foreign_key: :user_id
  has_many :category_bannings
  has_many :users, through: :category_bannings
  has_many :category_managements, dependent: :destroy
  has_many :morderators, through: :category_managements
  has_many :topics, dependent: :destroy
  has_many :posts, through: :topics

  validates :title, presence: true, length: {maximum: 250}, uniqueness: true
  validates :description, length: {maximum: 250}

  scope :publishes, ->{where status: :publish}

  delegate :total_views, to: :posts

  private

end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < BaseController
    before_action :find_category, only: %i(show edit update destroy add_or_minus_morderator ban_or_unban_authors)
    before_action :all_categories, only: %i(index new edit)
    before_action :find_user, only: %i(add_or_minus_morderator ban_or_unban_authors)

    def new
      @category = Category.new
    end

    def index
      respond_to do |format|
        format.html
        format.json { render json: CategoriesDatatable.new(view_context) }
      end
    end

    def show
      @morderators = search category.morderators
    end

    def edit
      all_morderators = category.morderators
      @morderators = search all_morderators
      @users = search User.where.not(id: all_morderators)
      
      all_banning_authors = Author.joins(:categories).where(categories: {id: category})
      @banning_authors = search all_banning_authors
      @authors = search Author.where.not(id: all_banning_authors)

      @action = params[:target]

      respond_to do |format|
        format.html
        format.js
      end
    end

    def create
      if current_user.categories.new(category_params).save
        message = "Tạo chuyên mục thành công"
        icon = "success"
        path = admins_categories_path
      else
        message = "Tạo chuyên mục thất bại"
        icon = "warning"
        path = "#"
      end

      @notification = notification(message, icon, path=path)

      respond_to do |format|
        format.js
      end
    end

    def update
      if category.update_attributes category_params
        redirect_to admins_categories_path
      else
        redirect_to admins_categories_path
      end
    end
  
    def destroy
      if category.posts.present?
        category.update(status: :unpublish)
        message = "Không thể xóa chuyên mục có bài viết!!! Đã chuyển trạng thái chuyên mục thành không công khai."
        icon = "warning"
      else
        category.destroy
        message = "Xóa chuyên mục thành công"
        icon = "success"
      end
      
      @notification = notification(message, icon, path=path)
      @class = "delete-" << params[:id]

      respond_to do |format|
        format.js
      end
    end

    def add_or_minus_morderator
      user.type = Morderator.name if user.type == Author.name
      ActiveRecord::Base.transaction do
        user.save(validate: false)
        find_user
        category_management = user.category_managements.where(category: category)
        begin
          if (turn_user = category_management.present?)
            category_management.destroy_all
            user.update(type: Author.name) unless user.category_managements.present?
          else
            user.category_managements.create category: category
          end
          status = 200
        rescue Exception
          message = "Đã có lỗi xảy ra!!!"
          icon = "warning"
          status = 500
        end
        @notification = notification(message, icon)

        respond_to do |format|
          if status == 200
            if turn_user
              format.html { render partial: "admins/users/user_item", locals: {user: user, add_morderator: true, source: category, action: :add} }
            else
              format.html { render partial: "admins/users/morderator_item", locals: {user: user, source: category} }
            end
          else
            format.json { render json: @notification }
          end
        end
      end
    end

    def ban_or_unban_authors
      ActiveRecord::Base.transaction do
        category_banning = user.category_bannings.where(category: category)
        begin
          if (unban_user = category_banning.present?)
            category_banning.destroy_all
          else
            user.category_bannings.create category: category
          end
          status = 200
        rescue Exception
          message = "Đã có lỗi xảy ra!!!"
          icon = "warning"
          status = 500
        end
        @notification = notification(message, icon)

        respond_to do |format|
          if status == 200
            if unban_user
              format.html { render partial: "admins/users/user_item", locals: {user: user, add_morderator: true, source: category, action: :ban} }
            else
              format.html { render partial: "admins/users/banning_authors", locals: {user: user, source: category, action: :unban} }
            end
          else
            format.json { render json: @notification }
          end
        end
      end
    end

    private

    attr_reader :category, :morderators, :categories, :user 

    def category_params
      category = params.require(:category).permit Category::CATEGORY_ATTRS
      category["status"] = category["status"].to_i
      category
    end

    def find_category
      @category = Category.find_by id: params[:id]
      return if category.present?
      redirect_to admins_categories_path
    end

    def all_categories
      @categories = Category.all
    end

    def find_user
      @user = User.find_by id: params[:user_id]
      return if user.present?
      redirect_to root_path
    end
  end
end

app/views/admins/categories/_categories_list.html.erb
<div class="white-box">
  <% if categories.present? %>
    <% categories.each do |category| %>
      <li>
        <%= link_to edit_admins_category_path(category), class: "waves-effect" do %>
          <%= category.title %>  <i class="fa <%= Settings.category.status[category.status] %> fa-fw" aria-hidden="true"></i>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <p>Không có chuyên mục nào</p>
  <% end %>
</div>

app/views/admins/categories/_categories_table.html.erb
<div>
  <%= content_tag :table, role: :datatable, class: "categories",data: { url: admins_categories_path(format: :json) } do %>
    <thead>
      <tr>
        <th>Tiêu đề</th>
        <th>Trạng thái</th>
        <th>Chủ đề</th>
        <th>Bài viết</th>
        <th>Lượt xem</th>
        <th>Moderators</th>
        <th>Uncheck</th>
        <th>Banning users</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    </tbody>
  <% end %>
</div>

app/views/admins/categories/_category_form.html.erb
<div class="white-box">
  <% if disable %>
    <fieldset disabled>
  <% end %>
  <%= form_for [:admins, category], html: {multipart: true, class: "form-horizontal form-material"}, remote: true do |f|%>
    <div class="form-group">
      <%= f.label "Tiêu đề", class: "col-md-12 required" %>
      <div class="col-md-12">
        <%= f.text_field :title, class: "form-control form-control-line", placeholder: "Nhập tiêu đề", required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Mô tả", class: "col-md-12" %>
      <div class="col-md-12">
        <%= f.text_area :description, class: "form-control form-control-line resize-vertical", placeholder: "Nhập mô tả", rows: 5 %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Trạng thái", class: "col-sm-12 required" %>
      <div class="col-sm-12">
        <%= f.select :status, Category.statuses, {}, {class: "form-control form-control-line"} %>
      </div>
    </div>
    <% if !disable %>
      <div class="form-group">
        <div class="col-sm-12">
          <%= f.submit yield(:title), class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if disable %>
    </fieldset>
  <% end %>
</div>

app/views/admins/categories/destroy.js.erb
async function notification(){
  await $.toast({
    text: '<%= @notification[:message]%>',
    position: 'top-right',
    loaderBg: '#fff',
    icon: '<%= @notification[:icon] %>',
    hideAfter: 3500,
    stack: 6
  });

  if('<%= @notification[:icon] %>' == 'success'){
    $('.<%= @class %>').remove();
  } else {
    $('.<%= @class %>>.status').attr('class', 'fa fa-times-circle');
  }
};

notification();

app/views/admins/categories/edit.html.erb
<% provide :title, "Cập nhật chuyên mục - #{@category.title}" %>
<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
</div>

<div class="col-md-8 col-xs-12">
  <%= render "admins/categories/category_form", category: @category, disable: false %>
</div>

<div class="row">
  <div class="col-md-12 col-lg-8 col-sm-12">
    <div class="white-box">
      <h3 class="box-title">DANH SÁCH NGƯỜI DÙNG</h3>
      <%= render "admins/users/search", link_path: edit_admins_category_path(@category), action: :add %>
      <div class="comment-center p-t-10 users-ajax-list">
        <%= render "admins/users/users_list", users: @users, add_morderator: true, source: @category, action: :add %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="panel">
      <div class="sk-chat-widgets">
        <div class="panel panel-default">
          <div class="panel-heading">
            DANH SÁCH MORDERATORS
            <%= render "admins/users/search", link_path: edit_admins_category_path(@category), action: :remove %>
          </div>
          <div class="panel-body">
            <%= render "admins/users/users_list", users: @morderators, add_morderator: true, source: @category, action: :remove %>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 col-lg-8 col-sm-12">
    <div class="white-box">
      <h3 class="box-title">DANH SÁCH TÁC GIẢ</h3>
      <%= render "admins/users/search", link_path: edit_admins_category_path(@category), action: :ban %>
      <div class="comment-center p-t-10">
        <%= render "admins/users/users_list", users: @authors, add_morderator: true, source: @category, action: :ban %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="panel">
      <div class="sk-chat-widgets">
        <div class="panel panel-default">
          <div class="panel-heading">
            DANH SÁCH BANNING USERS
            <%= render "admins/users/search", link_path: edit_admins_category_path(@category), action: :unban %>
          </div>
          <div class="panel-body">
            <%= render "admins/users/users_list", users: @banning_authors, add_morderator: true, source: @category, action: :unban %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/categories/edit.js.erb
$('.<%= Settings.target.classname[@action] %>-list').replaceWith(
  "<%= j render partial: 'admins/users/users_list', locals: { users: eval(Settings.target.variable[@action]),
    add_morderator: true, source: @category, action: @action } %>"
);

minus_morderators();
add_morderators();
ban_users();
unban_users();

app/views/admins/categories/index.html.erb
<% provide :title, "Danh sách chuyên mục"%>

<%= link_to "Tạo chuyên mục", new_admins_category_path,
  class: "btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light" %>
<div class="clearfix margin-bottom-20"></div>
<% if @categories.present? %>
  <%= render "admins/categories/categories_table", categories: @categories %>
<% else %>
  <p>Không có chuyên mục nào</p>
<% end %>

app/views/admins/categories/new.html.erb
<% provide :title, "Tạo chuyên mục"%>
<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
</div>

<div class="col-md-8 col-xs-12">
  <%= render "admins/categories/category_form", category: @category, disable: false %>
</div>

app/views/admins/categories/show.html.erb
<% provide :title, @category.title %>
<% topics = @category.topics %>
<%= link_to "Cập nhật chuyên mục", edit_admins_category_path(@category),
  class: "btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light" %>
<div class="clearfix margin-bottom-20"></div>
<%= render "admins/categories/category_form", category: @category, disable: true %>

<div class="whitebox">
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Chủ đề </h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= topics.size %></span></li>
      </ul>

      <%= render "admins/topics/topics_list", topics: topics %>
      <%= link_to "Quản lý chủ đề", admins_topics_path %>
    </div>
  </div>

  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Morderators</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @morderators.size %></span></li>
      </ul>

      <%= render "admins/users/users_list", users: @morderators, add_morderator: false, source: @category, action: :add %>

      <%= link_to "Thêm morderators", edit_admins_category_path(@category) %>
    </div>
  </div>

  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Bài viết</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @category.posts.size %></span></li>

        <li>
          <h3 class="box-title">Lượt xem</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @category.total_views %></span></li>
      </ul>

      <%= link_to "Quản lý bài viết", admins_topics_path %>
    </div>
  </div>

  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Banning users</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @category.users.size %></span></li>
      </ul>

      <%= link_to "Quản lý banning users", edit_admins_category_path(@category) %>
    </div>
  </div>
</div>