config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users

  root to: "static_pages#index"

  namespace :admins do
    root to: "dashboards#index"
    resources :categories
    resources :topics
    resources :posts do
      resources :votes, only: %i(create)
      resources :comments, only: %i(create show update destroy)
    end
    resources :morderators, only: %i(index show create destroy)
    resources :users
    resources :images, only: [:create]
    resources :notifications, only: [:update]

    get "user_info"
    get "add_or_minus_moderators/:user_id/category/:id", to: "categories#add_or_minus_morderator", as: "add_or_minus_morderator"
    get "ban_or_unban_authors/:user_id/category/:id", to: "categories#ban_or_unban_authors", as: "ban_or_unban_author"
    get "ban_or_unban_authors/:user_id/topic/:id", to: "topics#ban_or_unban_authors", as: "ban_or_unban_author_topic"
  end

  namespace :morderators do

  end

  namespace :authors do
    root to: "posts#index"

    resources :posts
    resources :topics
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable

  enum sex: %i(female male)

  has_many :category_bannings, dependent: :destroy
  has_many :topic_bannings, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images
  has_many :notifications

  # validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i}
  validates :phone, allow_nil: true, format: {with: /\A[[\+\-]?\d+]{10,20}\z/i}
  validates :sex, allow_nil: true, inclusion: {in: sexes.values}

  before_save :default_type

  scope :search, (lambda do |search=""|
    where("name LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%")
  end)

  def avatar
    self.images.where(current_avatar: true).first
  end

  private

  def default_type
    self.type ||= Author.name
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < BaseController
    before_action :find_category, :find_topic, only: %i(search)

    def info
      respond_to do |format|
        format.json {render json: current_user: current_user}
      end
    end
  
    def search
      @users = User.search params

      respond_to do |format|
        format.js
      end
    end

    private

    attr_reader :users, :category

    def find_category
      @category = Category.find_by id: params[:category_id]
    end

    def find_topic
      @category = Category.find_by id: params[:topic_id]
    end
  end
end

app/views/admins/users/_banning_authors.html.erb
<li>
  <div class="call-chat">
    <button class="btn btn-rounded btn-default btn-outline m-r-5 btn-lg"><i class="fa fa-user fa-user-color"></i></button>
    <button class="btn btn-rounded btn-default btn-outline m-r-5 btn-lg unload-<%= action %>-<%= Settings.target.action[action] %>" 
      data-source="<%= eval(Settings.target.link[action]) %>">
      <i class="fa fa-check"></i>
    </button>
  </div>
  <%= render "shared/avatar", user: user %> <span><%= user.name %>
  <br><small class="text-danger"><%= user.email %></small></span>
</li>

app/views/admins/users/_morderator_item.html.erb
<li>
  <div class="call-chat">
    <button class="btn btn-rounded btn-default btn-outline m-r-5 btn-lg"><i class="fa fa-user fa-user-color"></i></button>
    <button class="btn btn-rounded btn-default btn-outline m-r-5 btn-lg unload-minus-morderators" 
      data-source="<%= admins_add_or_minus_morderator_path(user, source) %>">
      <i class="fa fa-minus"></i>
    </button>
  </div>
  <%= render "shared/avatar", user: user %> <span><%= user.name %>
  <br><small class="text-danger"><%= user.email %></small></span>
</li>

app/views/admins/users/_search.html.erb
<%= form_tag link_path, method: :get, class: "app-search hidden-sm hidden-xs m-r-10", role: "search", remote: true do %>
  <div class="col-md-8">
    <%= text_field_tag :search, "", class: "form-control no-margin-top", placeholder: "Search" %>
  </div>
  <div class="col-md-4">
    <%= submit_tag "Tìm", class: "btn btn-warning search-submit", data: { disable_with: "Đang tìm.." } %>
  </div>
  <%= hidden_field_tag :target , action %>
<% end %>

app/views/admins/users/_user_item.html.erb
<div class="comment-body">
  <div class="user-img">
    <%= render "shared/avatar", user: user %>
  </div>
  <div class="mail-contnet">
    <h5>
      <%= user.name %>
      <i class="fa <%= Settings.morderators.sex[user.sex] %> fa-fw" aria-hidden="true"></i>
    </h5>
    <span class="time"><%= user.email %></span>
  </div>
  <% if add_morderator %>
    <button class="btn btn-rounded btn-default btn-outline m-r-5 btn-lg unload-<%= action %>-<%= Settings.target.action[action] %>" 
      data-source="<%= eval(Settings.target.link[action]) %>">
      <i class="fa <%= Settings.morderators.action[action] %>"></i>
    </button>
  <% end %>
</div>

app/views/admins/users/_users_list.html.erb
<div class="<%= Settings.target.classname[action] %>-list">
  <div class="<%= Settings.target.classstyle[action] %> <%= Settings.target.classname[action] %>-list-second">
    <% if users.present? %>
      <% users.each do |user| %>
        <%= render Settings.target.partial[action], user: user, add_morderator: add_morderator,
          source: source, action: action %>
      <% end %>
    <% end %>
  </div>

  <%= paginate users, params: {search_user: @search, target: action}, remote: true %>
</div>

app/views/admins/users/search.js.erb
$('.users-list').replaceWith(
  "<%= j render partial: 'admins/users/users_list', locals: { users: @users, add_morderator: true, source: @category, action: :add } %>"
);

minus_morderators();
add_morderators();
ban_users();
unban_users();