config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users

  root to: "static_pages#index"

  namespace :admins do
    root to: "dashboards#index"
    resources :categories
    resources :topics
    resources :posts do
      resources :votes, only: %i(create)
      resources :comments, only: %i(create show update destroy)
    end
    resources :morderators, only: %i(index show create destroy)
    resources :users
    resources :images, only: [:create]
    resources :notifications, only: [:update]

    get "user_info"
    get "add_or_minus_moderators/:user_id/category/:id", to: "categories#add_or_minus_morderator", as: "add_or_minus_morderator"
    get "ban_or_unban_authors/:user_id/category/:id", to: "categories#ban_or_unban_authors", as: "ban_or_unban_author"
    get "ban_or_unban_authors/:user_id/topic/:id", to: "topics#ban_or_unban_authors", as: "ban_or_unban_author_topic"
  end

  namespace :morderators do

  end

  namespace :authors do
    root to: "posts#index"

    resources :posts
    resources :topics
  end
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: %i(uncheck checked draft publish)

  POST_ATTRS = %w(id title description status content topic_id).freeze

  belongs_to :topic
  belongs_to :author, class_name: User.name, foreign_key: :user_id
  has_many :comments, dependent: :destroy
  has_many :votes, as: :ownerable, dependent: :destroy
  has_many :notifications, foreign_key: :target_id, dependent: :destroy

  validates :title, presence: true, length: {maximum: 250}
  validates :description, length: {maximum: 250}
  validates :content, presence: true, length: {maximum: 7500}

  after_update :create_notification

  delegate :category, to: :topic

  scope :total_views, ->{ sum :views }
  # scope :total_votes, ->{ joins(:votes).sum(:status) }

  def total_votes
    self.votes.sum(:status)
  end

  def create_notification
    return if self.publish?
    sender = self.author
    content = "đã cập nhật bài viết"
    User.joins(:comments).where(comments: {post_id: self.id}).distinct.each do |user|
      next if user.id == self.user_id
      noti = Notification.new user_id: user.id, status: 0, sender: sender.name,
        target: self.title, content: content, target_id: self.id, type_noti: 1
      noti.save if noti.check_noti?
    end
  end
end

app/controllers/admins/posts_controller.rb
module Admins
  class PostsController < BaseController
    before_action :posts, only: %i(index)
    before_action :find_post, only: %i(show edit update destroy)
    before_action :categories, :topics, only: %i(new edit)

    def index
      respond_to do |format|
        format.html
        format.json { render json: PostsDatatable.new(view_context) }
      end
    end

    def show
      post.views += 1
      post.save
    end

    def new
      @uploader = true
    end

    def create
      if current_user.posts.new(post_params).save
        message = "Tạo bài viết thành công"
        icon = "success"
        path = admins_posts_path
      else
        message = "Tạo bài viết thất bại"
        icon = "warning"
        path = "#"
      end

      @notification = notification(message, icon, path=path)

      respond_to do |format|
        format.js
      end
    end

    def edit; end

    def update
      if params[:editable].present?
        post.update_attributes post_params
        redirect_to [:admins, post]
      else
        ActiveRecord::Base.transaction do
          begin
            if params[:accept].to_i == 1
              post.update(status: :publish)
              message = "Đã chuyển trạng thái bài *#{post.title}* thành công khai"
              icon = "success"
            else
              post.update(status: :checked)
              message = "Đã chuyển trạng thái bài *#{post.title}* thành đã kiểm tra"
              icon = "success"
            end
          rescue
            message = "Đã có lỗi xảy ra"
            icon = "warning"
          end
        
          @notification = notification(message, icon)

          respond_to do |format|
            format.js
          end
        end
      end
    end

    def destroy
      post.destroy!
      message = "Đã xóa bài viết *#{post.title}* thành công"
      icon = "success"
      @notification = notification(message, icon)

      respond_to do |format|
        format.js
      end
    end

    private

    attr_reader :posts, :post, :topics, :categories

    def posts
      @posts = Post.all
    end

    def find_post
      @post = Post.find_by id: params[:id]

      return if post
      redirect_to admins_posts_path
    end

    def categories
      @categories = Category.all
    end

    def topics
      @topics = Topic.all
    end

    def post_params
      post = params.require(:post).permit Post::POST_ATTRS
      post["status"] = post["status"].to_i
      post
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < BaseController
    def index
      @posts = Post.where(status: :publish).includes(:comments, :votes, :author).page(params[:page] || 1).per(Settings.page.per_page)
    end

    def show

    end
  end
end

app/views/admins/posts/_post_form.html.erb
<% if disable %>
  <fieldset disabled>
<% end %>
<%= form_for [:admins, post], html: {multipart: true, class: "form-horizontal form-material"}, remote: true do |f|%>
  <div class="col-md-8 col-xs-12">
    <div class="white-box">
      <% if editable %>
        <%= hidden_field_tag "editable", editable %>
      <% end %>
      <div class="form-group">
        <%= f.label "Tiêu đề", class: "col-md-12 required" %>
        <div class="col-md-12">
          <%= f.text_field :title, class: "form-control form-control-line", placeholder: "Nhập tiêu đề", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag "Chuyên mục", nil, class: "col-sm-12 required" %>
        <div class="col-sm-12">
          <%= select_tag :category_id, options_for_select(categories.collect{|category| [category.title, category.id]}), class: "form-control form-control-line" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Chuyên mục", class: "col-sm-12 required" %>
        <div class="col-sm-12">
          <% categories.each do |category| %>
            <%= f.select :topic_id, category.topics.collect{|topic| [topic.title, topic.id]}, {},
              {class: "form-control form-control-line topic-#{category.id} topic-hide"} %>
          <% end %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Mô tả", class: "col-md-12" %>
        <div class="col-md-12">
          <%= f.text_area :description, class: "form-control form-control-line resize-vertical", placeholder: "Nhập mô tả", rows: 5 %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Trạng thái", class: "col-sm-12 required" %>
        <div class="col-sm-12">
          <%= f.select :status, Post.statuses, {}, {class: "form-control form-control-line"} %>
        </div>
      </div>

      <% if !disable %>
        <div class="form-group">
          <div class="col-sm-12">
            <%= f.submit yield(:title), class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    
      <% if disable %>
        </fieldset>
      <% end %>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="form-group">
    <%= f.label "Nội dung", class: "col-md-12 required" %>
    <div class="col-md-12">
      <%= f.text_area :content, class: "form-control form-control-line resize-vertical", placeholder: "Nhập mô tả", id: "markdown" %>
    </div>
  </div>
<% end %>

app/views/admins/posts/_post_row.html.erb
<td class="sorting_1"><%= record.title %></td>
<td><%= record.status %> <i class="fa <%= Settings.post.status[record.status] %> status"></i></td>
<td><%= record.author.name %></td>
<td><%= record.views %></td>
<td><%= record.topic.title %></td>
<td><%= record.category.title %></td>
<td><%= record.total_votes %></td>
<td><%= record.comments.size %></td>
<td><%= record.created_at.strftime(Settings.post.time_format) %></td>
<td>
  <%= link_to("Xem", [:admins, record]) %> | 
  <% if record.uncheck? %>
    <%= link_to("Duyệt", admins_post_path(record, accept: 1), method: :patch, remote: true) %>
    <%= link_to("Không duyệt", admins_post_path(record, accept: 0), method: :patch, remote: true) %>
  <% else %>
    <%= link_to((record.publish? ? "Không duyệt" : "Duyệt"), admins_post_path(record, accept: record.publish? ? 0 : 1), method: :patch, remote: true) %>
  <% end %> | 
  <%= link_to("Xóa", [:admins, record], method: :delete, data: { confirm: "Bạn chắc chứ?" }, class: "link-remote", id: "delete-#{record.id}", remote: true) %>
</td>

app/views/admins/posts/_posts_table.html.erb
<div>
  <%= content_tag :table, role: :datatable, class: "posts",data: { url: admins_posts_path(format: :json) } do %>
    <thead>
      <tr>
        <th>Tiêu đề</th>
        <th>Trạng thái</th>
        <th>Tác giả</th>
        <th>Lượt xem</th>
        <th>Chủ đề</th>
        <th>Chuyên mục</th>
        <th>Votes</th>
        <th>Bình luận</th>
        <th>Ngày tạo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    </tbody>
  <% end %>
</div>

app/views/admins/posts/_vote.html.erb
<div class="main">
  <%= link_to admins_post_votes_path(post, status: 1), remote: true, multipart: true, method: :post do %>
    <button id="upButton" type="button"
      class="vote <%= "up-active" if post.votes.find_by(user: current_user, status: 1).present? %>">
      <i class="fa fa-angle-up upArrow"></i>
    </button>
  <% end %>

  <h3 id="scoreCounter"><%= post.total_votes %></h3>

  <%= link_to admins_post_votes_path(post, status: -1), remote: true, multipart: true, method: :post do %>
    <button id="downButton" type="button"
      class="vote <%= "down-active" if post.votes.where(user: current_user, status: -1).present? %>">
      <i class="fa fa-angle-down downArrow"></i>
    </button>
  <% end %>
</div>

app/views/admins/posts/create.js.erb
async function notification(){
  $.toast({
    text: '<%= @notification[:message]%>',
    position: 'top-right',
    loaderBg: '#fff',
    icon: '<%= @notification[:icon] %>',
    hideAfter: 3500,
    stack: 6
  });
  await sleep(1000);
  window.location.href = '<%= @notification[:path] %>';
};

notification();

app/views/admins/posts/destroy.js.erb
async function notification(){
  await $.toast({
    text: '<%= @notification[:message]%>',
    position: 'top-right',
    loaderBg: '#fff',
    icon: '<%= @notification[:icon] %>',
    hideAfter: 3500,
    stack: 6
  });
};

$('.delete-<%= @post.id %>').remove();

notification();

app/views/admins/posts/edit.html.erb
<% provide :title, "Cập nhật bài viết" %>

<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
  <%= render "admins/topics/topics_list", topics: @topics %>
</div>

<%= render "admins/posts/post_form", post: @post, topics: @topics, categories: @categories, disable: false, editable: true %>

app/views/admins/posts/index.html.erb
<% provide :title, "Danh sách bài viết" %>

<%= link_to "Tạo bài viết", new_admins_post_path,
  class: "btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light" %>
<div class="clearfix margin-bottom-20"></div>
<% if @posts.present? %>
  <%= render "admins/posts/posts_table", posts: @posts %>
<% else %>
  <p>Không có chuyên mục nào</p>
<% end %>

app/views/admins/posts/new.html.erb
<% provide :title, "Tạo bài viết mới" %>

<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
  <%= render "admins/topics/topics_list", topics: @topics %>
</div>

<%= render "admins/posts/post_form", post: Post.new, topics: @topics, categories: @categories, disable: false, editable: false %>

app/views/admins/posts/show.html.erb
<% provide :title, "#{@post.topic.category.title} - #{@post.topic.title}" %>

<div class="post-info white-box" data-post-id="<%= @post.id %>" data-user-id="<%= current_user.id %>">
  <div class="col-md-8 col-xs-8 col-sm-8">
    <h2><%= @post.title %></h2>
    <span class="post-time"><%= @post.author.name %></span>
    <% if current_user == @post.author %>
      <%= link_to edit_admins_post_path(@post) do %>
        <span><li class="fa fa-edit"></li></span>
      <% end %>
    <% end %>
    <span class="post-time">đã viết vào ngày <%= @post.created_at.strftime(Settings.post.time_format) %></span>
    <br>
    <i class="fa fa-eye post-time"></i><span><%= @post.views %></span>
    <i class="fa  fa-comments-o post-time"></i><span><%= @post.comments.size %></span>
  </div>
  <div class="col-md-4 second col-xs-4 col-sm-4">
    <%= render "admins/posts/vote", post: @post %>
  </div>
  <div class="clearfix"></div>
</div>
<div class="markdown">
  <%= markdown @post.content %>
</div>

<div>
  <%= render "admins/comments/comment_box", comments: @post.comments.includes(:user, user: :images), post: @post %>
</div>

app/views/admins/posts/update.js.erb
async function notification(){
  await $.toast({
    text: '<%= @notification[:message]%>',
    position: 'top-right',
    loaderBg: '#fff',
    icon: '<%= @notification[:icon] %>',
    hideAfter: 3500,
    stack: 6
  });
};

$('.update-<%= @post.id %>').empty();
$('.update-<%= @post.id %>').html(
  "<%= j render partial: "admins/posts/post_row", locals: {record: @post} %>"
);

notification();