config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users

  root to: "static_pages#index"

  namespace :admins do
    root to: "dashboards#index"
    resources :categories
    resources :topics
    resources :posts do
      resources :votes, only: %i(create)
      resources :comments, only: %i(create show update destroy)
    end
    resources :morderators, only: %i(index show create destroy)
    resources :users
    resources :images, only: [:create]
    resources :notifications, only: [:update]

    get "user_info"
    get "add_or_minus_moderators/:user_id/category/:id", to: "categories#add_or_minus_morderator", as: "add_or_minus_morderator"
    get "ban_or_unban_authors/:user_id/category/:id", to: "categories#ban_or_unban_authors", as: "ban_or_unban_author"
    get "ban_or_unban_authors/:user_id/topic/:id", to: "topics#ban_or_unban_authors", as: "ban_or_unban_author_topic"
  end

  namespace :morderators do

  end

  namespace :authors do
    root to: "posts#index"

    resources :posts
    resources :topics
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  enum status: %i(unpublish publish close)

  TOPIC_ATTRS = %w(id title description status user_id category_id).freeze

  belongs_to :user
  belongs_to :category
  has_many :votes, as: :ownerable, dependent: :destroy
  has_many :posts
  has_many :topic_bannings
  has_many :users, through: :topic_bannings

  delegate :total_views, to: :posts

  def total_votes
    self.votes.sum(:status)
  end
end

app/controllers/admins/topics_controller.rb
module Admins
  class TopicsController < BaseController
    before_action :all_topic, only: %i(index show edit)
    before_action :categories, only: %i(new show edit)
    before_action :find_topic, only: %i(show edit update destroy ban_or_unban_authors)
    before_action :find_user, only: %i(ban_or_unban_authors)

    def index
      respond_to do |format|
        format.html
        format.json { render json: TopicsDatatable.new(view_context) }
      end
    end

    def show
      @posts = topic.posts
    end

    def new; end

    def create
      if current_user.topics.new(topic_params).save
        message = "Tạo chủ đề thành công"
        icon = "success"
        path = admins_topics_path
      else
        message = "Tạo chủ đề thất bại"
        icon = "warning"
        path = "#"
      end

      @notification = notification(message, icon, path=path)

      respond_to do |format|
        format.js
      end
    end

    def edit
      all_banning_authors = Author.joins(:topics).where(topics: {id: topic})
      @banning_authors = search all_banning_authors
      @authors = search Author.where.not(id: all_banning_authors)

      @action = params[:target]

      respond_to do |format|
        format.html
        format.js
      end
    end

    def update
    end

    def destroy
      if topic.posts.present?
        topic.update(status: :unpublish)
        message = "Không thể xóa chuyên mục có bài viết!!! Đã chuyển trạng thái chuyên mục thành không công khai."
        icon = "warning"
      else
        topic.destroy
        message = "Xóa chuyên mục thành công"
        icon = "success"
      end
      
      @notification = notification(message, icon, path=path)
      @class = "delete-" << params[:id]

      respond_to do |format|
        format.js
      end
    end

    def ban_or_unban_authors
      ActiveRecord::Base.transaction do
        topic_banning = user.topic_bannings.where(topic: topic)

        begin
          if (unban_user = topic_banning.present?)
            topic_banning.destroy_all
          else
            user.topic_bannings.create topic: topic
          end
          status = 200
        rescue Exception
          message = "Đã có lỗi xảy ra!!!"
          icon = "warning"
          status = 500
        end
        @notification = notification(message, icon)

        respond_to do |format|
          if status == 200
            if unban_user
              format.html { render partial: "admins/users/user_item", locals: {user: user, add_morderator: true, source: topic, action: :topic_ban} }
            else
              format.html { render partial: "admins/users/banning_authors", locals: {user: user, source: topic, action: :topic_unban} }
            end
          else
            format.json { render json: @notification }
          end
        end
      end
    end

    private

    attr_reader :topics, :topic, :user

    def topic_params
      topic = params.require(:topic).permit Topic::TOPIC_ATTRS
      topic["status"] = topic["status"].to_i
      topic
    end

    def all_topic
      @topics = Topic.all
    end

    def categories
      @categories = Category.all
    end

    def find_topic
      @topic = Topic.find_by id: params[:id]
      return if topic
      redirect_back fallback_location: admins_topics_path
    end

    def find_user
      @user = Author.find_by id: params[:user_id]
      return if user
      redirect_back fallback_location admins_topics_path
    end
  end
end

app/views/admins/topics/_topic_form.html.erb
<div class="white-box">
  <% if disable %>
    <fieldset disabled>
  <% end %>
  <%= form_for [:admins, topic], html: {multipart: true, class: "form-horizontal form-material"}, remote: true do |f|%>
    <div class="form-group">
      <%= f.label "Tiêu đề", class: "col-md-12 required" %>
      <div class="col-md-12">
        <%= f.text_field :title, class: "form-control form-control-line", placeholder: "Nhập tiêu đề", required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Chuyên mục", class: "col-sm-12 required" %>
      <div class="col-sm-12">
        <%= f.select :category_id, categories.collect{|category| [category.title, category.id]}, {}, {class: "form-control form-control-line"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Mô tả", class: "col-md-12" %>
      <div class="col-md-12">
        <%= f.text_area :description, class: "form-control form-control-line resize-vertical", placeholder: "Nhập mô tả", rows: 5 %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Trạng thái", class: "col-sm-12 required" %>
      <div class="col-sm-12">
        <%= f.select :status, Topic.statuses, {}, {class: "form-control form-control-line"} %>
      </div>
    </div>

    <% if !disable %>
      <div class="form-group">
        <div class="col-sm-12">
          <%= f.submit yield(:title), class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if disable %>
    </fieldset>
  <% end %>
</div>

app/views/admins/topics/_topics_list.html.erb
<div class="white-box">
  <% if topics.present? %>
    <% topics.each do |topic| %>
      <li>
        <%= link_to "#", class: "waves-effect" do %>
          <%= topic.title %>  <i class="fa <%= Settings.topic.status[topic.status] %> fa-fw" aria-hidden="true"></i>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <p>Không có chủ đề nào</p>
  <% end %>
</div>

app/views/admins/topics/_topics_table.html.erb
<div>
  <%= content_tag :table, role: :datatable, class: "topics", data: { url: admins_topics_path(format: :json) } do %>
    <thead>
      <tr>
        <th>Tiêu đề</th>
        <th>Trạng thái</th>
        <th>Chuyên mục</th>
        <th>Bài viết</th>
        <th>Uncheck</th>
        <th>Banning users</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    </tbody>
  <% end %>
</div>

app/views/admins/topics/destroy.js.erb
async function notification(){
  await $.toast({
    text: '<%= @notification[:message]%>',
    position: 'top-right',
    loaderBg: '#fff',
    icon: '<%= @notification[:icon] %>',
    hideAfter: 3500,
    stack: 6
  });

  if('<%= @notification[:icon] %>' == 'success'){
    $('.<%= @class %>').remove();
  } else {
    $('.<%= @class %>>.status').attr('class', 'fa fa-times-circle');
  }
};

notification();

app/views/admins/topics/edit.html.erb
<% provide :title, "Cập nhật chủ đề - #{@topic.title}" %>
<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
  <%= render "admins/topics/topics_list", topics: @topics %>
</div>

<div class="col-md-8 col-xs-12">
  <%= render "admins/topics/topic_form", topic: @topic, categories: @categories, disable: false %>
</div>

<div class="row">
  <div class="col-md-12 col-lg-8 col-sm-12">
    <div class="white-box">
      <h3 class="box-title">DANH SÁCH TÁC GIẢ</h3>
      <%= render "admins/users/search", link_path: edit_admins_topic_path(@topic), action: :topic_ban %>
      <div class="comment-center p-t-10">
        <%= render "admins/users/users_list", users: @authors, add_morderator: true, source: @topic, action: :topic_ban %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="panel">
      <div class="sk-chat-widgets">
        <div class="panel panel-default">
          <div class="panel-heading">
            DANH SÁCH BANNING USERS
            <%= render "admins/users/search", link_path: edit_admins_topic_path(@topic), action: :topic_unban %>
          </div>
          <div class="panel-body">
            <%= render "admins/users/users_list", users: @banning_authors, add_morderator: true, source: @topic, action: :topic_unban %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/topics/edit.js.erb
$('.<%= Settings.target.classname[@action] %>-list').replaceWith(
  "<%= j render partial: 'admins/users/users_list', locals: { users: eval(Settings.target.variable[@action]), add_morderator: true, source: @topic, action: @action } %>"
);

ban_users_topic();
unban_users_topic();

app/views/admins/topics/index.html.erb
<% provide :title, "Danh sách chủ đề"%>

<%= link_to "Tạo chủ đề", new_admins_topic_path,
  class: "btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light" %>
<div class="clearfix margin-bottom-20"></div>
<% if @topics.present? %>
  <%= render "admins/topics/topics_table", topics: @topics %>
<% else %>
  <p>Không có chuyên mục nào</p>
<% end %>

app/views/admins/topics/new.html.erb
<% provide :title, "Tạo chủ đề"%>
<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
</div>

<div class="col-md-8 col-xs-12">
  <%= render "admins/topics/topic_form", topic: Topic.new, categories: @categories, disable: false %>
</div>

app/views/admins/topics/show.html.erb
<% provide :title, "Cập nhật chủ đề - #{@topic.title}" %>
<%= link_to "Cập nhật chủ đề", edit_admins_topic_path(@topic),
  class: "btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light" %>
<div class="clearfix margin-bottom-20"></div>
<div class="col-md-4 col-xs-12">
  <%= render "admins/categories/categories_list", categories: @categories %>
  <%= render "admins/topics/topics_list", topics: @topics %>
</div>

<div class="col-md-8 col-xs-12">
  <%= render "admins/topics/topic_form", topic: @topic, categories: @categories, disable: true %>
</div>

<div class="whitebox">
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Bài viết</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @posts.size %></span></li>
      </ul>

      <%= render "admins/posts/posts_list", posts: @posts %>
      <%= link_to "Quản lý bài viết", admins_posts_path %>
    </div>
  </div>

  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Số votes</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @topic.total_votes %></span></li>

        <li>
          <h3 class="box-title">Lượt xem</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @topic.total_views %></span></li>
      </ul>
    </div>
  </div>

  <div class="col-lg-4 col-sm-6 col-xs-12">
    <div class="white-box analytics-info">
      <ul class="list-inline two-part">
        <li>
          <h3 class="box-title">Banning users</h3>
        </li>
        <li class="text-right"><span class="counter text-success"><%= @topic.users.size %></span></li>
      </ul>

      <%= link_to "Quản lý banning users", edit_admins_topic_path(@topic) %>
    </div>
  </div>
</div>